FROM dunglas/frankenphp:1.4-php8.4


# 安裝PHP需要的套件
RUN install-php-extensions \
    zip \
    gd \
    curl \
    pdo_mysql \
    pdo_pgsql \
    intl \
    opcache

# 安裝Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer