services:
  mysql:
    image: mysql:5.7
    container_name: shop_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: localhost
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] 
      interval: 10s 
      timeout: 10s 
      retries: 5
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
  php:
    build: { 
      dockerfile: ./docker/php/dockerfile 
    }
    container_name: shop_php
    ports:
      - 9000:9000
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /var/www/html
    entrypoint: [ 'sh', './docker/php/init.sh' ]
    volumes:
      - ./:/var/www/html
  nginx:
    image: nginx
    container_name: shop_nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/shop.conf:/etc/nginx/conf.d/shop.conf