services:
    app:
        build: { dockerfile: ./docker/app/dockerfile }
        container_name: ${DOCKER_NAME}_app
        networks:
            - network
        ports:
            - ${DOCKER_APP_PORT}:80
        working_dir: /app
        entrypoint: ["sh", "./docker/app/init.sh"]
        volumes:
            - ./:/app
    scheduler:
        build: { dockerfile: ./docker/scheduler/dockerfile }
        container_name: ${DOCKER_NAME}_scheduler
        networks:
            - network
        working_dir: /app
        entrypoint: ["cron", "-f"]
        volumes:
            - ./:/app
            - ./docker/scheduler/scheduler.cron:/etc/cron.d/scheduler:ro
        depends_on:
            - app
networks:
    network:
        external: true
