name: "自動部署至GCE"

# 觸發條件
on:
  push:
    branches:
      - "feature/2.0"
# 執行工作
jobs:
  # 測試
  test:
    # 工作名稱
    name: "測試"

    # 作業系統
    runs-on: "ubuntu-latest"

    # 步驟
    steps:
      # 下載原始碼
      - name: "下載原始碼"
        uses: "actions/checkout@v4"

      # 加入PHP環境
      - name: "加入PHP環境"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          coverage: none

      # 用Composer安裝套件
      - name: "用Composer安裝套件"
        run: composer install

      # 執行測試
      - name: "執行測試"
        run: php artisan test tests/Unit
  # 部署
  build-and-deploy:
    # 工作名稱
    name: "部署"

    # 作業系統
    runs-on: "ubuntu-latest"

    # 需完成步驟
    needs: test

    # 步驟
    steps:
      # 驗證GCP權限
      - name: "驗證GCP權限"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"

      # 加入Gcloud CLI
      - name: "加入Gcloud CLI"
        uses: "google-github-actions/setup-gcloud@v2"

      # 部署GCE中的專案
      - name: "部署GCE中的專案"
        run: |
          gcloud compute ssh ${{ secrets.GCE_NAME }} --zone=${{ secrets.GCE_ZONE }} --command="
            # 切換至專案目錄
            cd /var/www/${{ secrets.APP_URL }}

            # 更新程式
            sudo git fetch origin feature/2.0
            sudo git checkout -f feature/2.0
            sudo git reset --hard origin/feature/2.0
            
            # 更新套件
            sudo docker compose exec app composer install
            
            # 更新資料庫
            sudo docker compose exec app php artisan migrate
            
            # 更新快取 
            sudo docker compose exec app php artisan config:cache
            sudo docker compose exec app php artisan route:cache
            sudo docker compose exec app php artisan view:cache
          "
  # 檢查
  health-check:
    # 工作名稱
    name: "檢查"

    # 作業系統
    runs-on: "ubuntu-latest"

    # 需完成步驟
    needs: build-and-deploy

    # 步驟
    steps:
      # 檢查
      - name: "檢查"
        run: |
          # 檢查最多嘗試5次
          for i in {1..5}; do
            # 發送檢查請求
            HTTP_CODE=$(curl -w "%{http_code}" https://${{ secrets.APP_URL }}/api/health)
            
            # 若檢查成功則離開
            if [ "$HTTP_CODE" = "204" ]; then
              exit 0
            fi
            
            # 檢查失敗則10秒後重新嘗試
            sleep 10
          done
          exit 1
      # 成功通知
      - name: "成功通知"
        if: success()
        run: |
          # 取得當前時間
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S")

          # 產生通知JSON
          # 如過不採用產生檔案的方式，會因為date指令導致錯誤
          cat > payload.json <<EOF
          {
            "embeds": [{
              "description": "# 📢 系統通知\n### 自動部署",
              "color": 3066993,
              "fields": [
                {
                  "name": "** 🌐 環境 **",
                  "value": "`${{ secrets.APP_URL }}`"
                },
                {
                  "name": "** ℹ️ 狀態 **",
                  "value": "`成功`"
                },
                {
                  "name": "** ⏰ 通知時間 **",
                  "value": "`${TIMESTAMP}`"
                }
              ]
            }]
          }
          EOF

          # 發送通知
          curl -H "Content-Type: application/json" \
               -d @payload.json \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
      # 失敗通知
      - name: "失敗通知"
        if: failure()
        run: |
          # 取得當前時間
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S")

          # 產生通知JSON
          # 如過不採用產生檔案的方式，會因為date指令導致錯誤
          cat > payload.json <<EOF
          {
            "embeds": [{
              "description": "# 📢 系統通知\n### 自動部署",
              "color": 15158332,
              "fields": [
                {
                  "name": "** 🌐 環境 **",
                  "value": "`${{ secrets.APP_URL }}`"
                },
                {
                  "name": "** ℹ️ 狀態 **",
                  "value": "`失敗`"
                },
                {
                  "name": "** ⏰ 通知時間 **",
                  "value": "`${TIMESTAMP}`"
                }
              ]
            }]
          }
          EOF

          # 發送通知
          curl -H "Content-Type: application/json" \
               -d @payload.json \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
